In [1]:
import numpy as np

In [2]:
a=np.array([1,3,5,7,9])
a

array([1, 3, 5, 7, 9])

In [3]:
a.ndim

1

In [4]:
b=np.array([[1,2],[3,2]])
b

array([[1, 2],
       [3, 2]])

In [5]:
b.ndim

2

In [6]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
c.ndim

2

In [8]:
c.shape

(3, 3)

In [9]:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
d.shape

(2, 2, 2)

In [11]:
#zeros

zeros1=np.zeros(5)
print(zeros1)

[0. 0. 0. 0. 0.]


In [12]:
zeros1=np.zeros(5,dtype=int)
print(zeros1)


[0 0 0 0 0]


In [13]:
zeros1=np.zeros([2,3,3],dtype=int)
print(zeros1)


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [14]:
zeros1=np.zeros([5,3])
print(zeros1)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
ones1=np.ones(3)
print(ones1)

[1. 1. 1.]


In [16]:
ones1=np.ones([2,3])
print(ones1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
ones1=np.ones([2,3,2])
print(ones1)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [18]:
iden=np.identity(5)
print(iden)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
iden=np.eye(4)
print(iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
n=np.array([1,3,5,7,9,12,25])
n[1]
n[1:4]

array([3, 5, 7])

In [21]:
n[-6:-3]

array([3, 5, 7])

In [22]:
n[::-1]

array([25, 12,  9,  7,  5,  3,  1])

In [23]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
m

#5
m[1,1]

#9
m[2,2]

#1
m[0,0]

#3
m[0,2]

3

In [24]:
m[1,:2]
m[1:,0]
m[1:,1:]



array([[5, 6],
       [8, 9]])

In [25]:
b=np.array([[1,2,5,6],[9,0,3,4],[10,7,11,15],[19,12,16,20]])
b

array([[ 1,  2,  5,  6],
       [ 9,  0,  3,  4],
       [10,  7, 11, 15],
       [19, 12, 16, 20]])

In [26]:
#[10,7,11,15]
b[2]




#[2,0,7,12]
b[0:,1]


#[[1,2],[9,0],[10,7],[19,12]]
b[:4,:2]


#[[2,5],[0,3]]
b[:2,1:3]

#[[11,15],[16,20]]
b[2:,2:]

array([[11, 15],
       [16, 20]])

In [27]:
s=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
s

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
#8
s[1,1,1]

8

In [29]:
#2
s[0,0,1]

2

In [30]:
#5
s[1,0,0]

5

In [31]:
#6
s[1,0,1]

6

# **Functions**

In [32]:
#arange()

a=np.arange(10)
print(a)
b=np.arange(1,10,2)
b

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

In [33]:
type(a)

numpy.ndarray

In [34]:
#reshape()

c=a.reshape(2,5)
print(c)
d=a.reshape(5,2,1)
print(d)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]

 [[8]
  [9]]]


In [35]:
#create a 1D array contains all the multiples of 3 upto 36 using arange()
#create all possible 2D and 3D arrays using reshape()


f=np.arange(3,37,3)
f
s=f.reshape(4,3)
print(s)
r=f.reshape(3,4)
print(r)
t=f.reshape(2,3,2)
print(t)
u=f.reshape(2,2,3)
print(u)
v=f.reshape(3,2,2)
print(v)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]
 [30 33 36]]
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]
[[[ 3  6]
  [ 9 12]
  [15 18]]

 [[21 24]
  [27 30]
  [33 36]]]
[[[ 3  6  9]
  [12 15 18]]

 [[21 24 27]
  [30 33 36]]]
[[[ 3  6]
  [ 9 12]]

 [[15 18]
  [21 24]]

 [[27 30]
  [33 36]]]


In [36]:
#flatten()--> converting to 1 dimension
f.flatten()

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36])

In [37]:
s.max()
print(s.max(axis=1))  #--> max in each row
print(s.max(axis=0))  #--> max in each col
print(s.min())
print(s.min(axis=1))
print(s.min(axis=0))

[ 9 18 27 36]
[30 33 36]
3
[ 3 12 21 30]
[3 6 9]


In [38]:
# argmax()  --> return the index count of max value element
print(s.argmax())
print(s.argmax(axis=1)) # returns index of max value in each row
print(s.argmax(axis=0))

11
[2 2 2 2]
[3 3 3]


In [39]:
print(s.argmin())
print(s.argmin(axis=1))
print(s.argmin(axis=0))

0
[0 0 0 0]
[0 0 0]


In [41]:
k=np.array([[1,2],[3,4]])
k

array([[1, 2],
       [3, 4]])

In [42]:
l=np.array([[5,6],[1,3]])
l

array([[5, 6],
       [1, 3]])

In [44]:
print(k+l)
print(k-l)

[[6 8]
 [4 7]]
[[-4 -4]
 [ 2  1]]


In [46]:
print(k*l)  #returns ele by ele multiplication,so use dot()
print(k.dot(l))

[[ 5 12]
 [ 3 12]]
[[ 7 12]
 [19 30]]


# **Trigonometric** **functions**

In [47]:
np.sin(k)   #--> returns radian value of corresponding numbers

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [48]:
np.cos(k)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [49]:
np.sqrt(k)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [50]:
k+2

array([[3, 4],
       [5, 6]])

In [51]:
k*2

array([[2, 4],
       [6, 8]])

In [53]:
m=np.array([[1.2,1.5,2.6],[2.4,2.8,2.5],[3.5,3.9,3.2],[4.1,4.5,4.8]])
m

array([[1.2, 1.5, 2.6],
       [2.4, 2.8, 2.5],
       [3.5, 3.9, 3.2],
       [4.1, 4.5, 4.8]])

In [54]:
np.ceil(m) #--> round off to next int

array([[2., 2., 3.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.]])

In [55]:
np.floor(m) #--> ignores the decimal part

array([[1., 1., 2.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [56]:
np.round(m) #--> round off to nearest even int

array([[1., 2., 3.],
       [2., 3., 2.],
       [4., 4., 3.],
       [4., 4., 5.]])